development:
  host: 127.0.0.1
  username: admin
  password: 123456
  encoding: utf8
  database: projects_development

test:
  host: 127.0.0.1
  username: admin
  password: 123456
  encoding: utf8
  database: projects_test

production:
  host: mongodb0.locum.ru
  username: onfly_projects49
  password: f5FQQDNb
  encoding: utf8
  database: onfly_projects49

